### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by LaloHao** [yify-pop/yify-pop#132]
I get this error on browser when i open http://localhost:4000

Error: 500 Internal Server Error
Error at createConstructor (/usr/lib/node_modules/geddy/lib/response/errors.js:68:34) at new <anonymous> (/usr/lib/node_modules/geddy/lib/response/errors.js:79:33) at Object.<anonymous> (/usr/lib/node_modules/geddy/lib/response/errors.js:21:10) at Module._compile (module.js:435:26) at Object.Module._extensions..js (module.js:442:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:311:12) at Module.require (module.js:366:17) at require (module.js:385:17) at Object.<anonymous> (/usr/lib/node_modules/geddy/lib/controller/responder/index.js:6:14) 

And here's what i get on geddy
```
Error
    at createConstructor (/usr/lib/node_modules/geddy/lib/response/errors.js:68:34)
    at new <anonymous> (/usr/lib/node_modules/geddy/lib/response/errors.js:79:33)
    at Object.<anonymous> (/usr/lib/node_modules/geddy/lib/response/errors.js:21:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/geddy/lib/controller/responder/index.js:6:14)
```

**Comment by hugoper** [comment]
same here.-

**Comment by arnotae** [comment]
I've had : 
```
Error: 500 Internal Server Error
TypeError: Cannot set property 'movie_count' of undefined at Request._callback (yify-pop/app/controllers/movies.js:45:41)
```

And I've corrected with : 

File -> yify-pop/app/controllers/movies.js on line 45

```javascript
yifyResponse = {data: {movie_count:0, movies:[]}};
//yifyResponse.data.movie_count = 0;
//yifyResponse.data.movies = [];
```

**Comment by LaloHao** [comment]
Neither Popcorn Time nor Kodi works anymore either

It seems yts.to (site that handles fetching) was taken down

http://www.forbes.com/sites/matthickey/2015/10/21/a-major-netflix-competitor-is-down-and-perhaps-out/

**Comment by Oliver84** [comment]
Any way around this or do we just need to wait for them to come back up?

**Comment by marioaugustorama** [comment]
The url used for parse movies and series come down!
https://yts.to/api/v2/

Anyone know another service that can use as a substitute.

**Comment by LaloHao** [comment]
We need to wait, apparently YTS is reestructuring, preparing themselves for the TPP/TTIP since the new deals seem to be dangerous to this kind of services

https://www.reddit.com/r/PopCornTime/comments/3pkphe/website_is_down_we_are_restructioning_please_calm/

**Comment by NaKroTeK** [comment]
@marioaugustorama apparently there is this API : torrentsapi
source : https://www.reddit.com/r/PopCornTime/comments/3qgve1/any_chance_of_a_new_movie_api_workaround/cwgk9tn

I did not try it yet.(Still figuring out how to do it ;) )

**Comment by kernelcoffee** [comment]
Looks like a new API is required: https://torrentfreak.com/yify-yts-shuts-down-the-end-of-a-piracy-icon-151030/

**Comment by Porco-Rosso** [comment]
can't attest to the reliability, as it has been down for awhile until now, but how about: https://getstrike.net/api/

**Comment by psycholyzern** [comment]
so...project dead?

**Comment by dfmcphee** [comment]
I have started a new project that is based around RSS feeds for torrents as a replacement for this. It is still very much a WIP but you can check it out here: https://github.com/dfmcphee/tvrrent

**Comment by psycholyzern** [comment]
nice!!
btw, maybe you should see ```yts.ag```
I was using them to access old yify encoded movies, but at that time, their api wont work. Somehow I tested today, their api showing output.

**Comment by kernelcoffee** [comment]
The issue is that right now there is no stable API available that will provide similar service as yfs.
BTW: yfs is dead, they made a deal to kill their service, anything that looks like yfs, it's not (copycat or scammers).
There is some work going on the PT reddit page (https://www.reddit.com/r/PopCornTime/) to provide workarounds for the yfs API but most of the API that pop-out fell down ever since.
But overall the backend of the project will need to be reworked to handle the change (some workaround available are through the Tor network).
For me the long term issue is not much the API which will come back in some other form in the near-medium futur but the content as yfs was providing clean and stable releases of disputable quality for the living room but great for streaming (average 1.3GB for 1080p) on mobile devices with the added benefice of a usable API.
That will be tough to replace.

**Comment by dfmcphee** [comment]
That was my thinking when building tvrrent. I didn't want to rely on third party APIs anymore. Using RSS feeds instead you can plug in in whatever feed you want like https://showrss.info/, or generate your own that it uses.

**Comment by LaloHao** [comment]
I am thinking that TPP/TIPP will make it harder for anyone to provide those services, so maybe we should instead try and make a (yts like) "local database" which could be transmitted through torrent so they can't take it down

**Comment by NaKroTeK** [comment]
It's how torrent site kinda work today, with choice to choose wich database
you want.

**Comment by albabosh** [comment]
Is there a yify api server source available ?

**Comment by albabosh** [comment]
Does anyone tried using yts.ag API ?

**Comment by pbourgeat** [comment]
As a temporary patch, I've partially implemented the new tv/movie API (based on https://www.reddit.com/r/PopCornTime/comments/3sbsz6/download_working_installers_or_fix_your_current/)

Movie searches and the various sorting don't work yet, but everything else seems to be working

https://github.com/yify-pop/yify-pop/pull/134
