### ISSUE TITLE
Forever not working

### ISSUE THREAD

**Issue by my90558** [yify-pop/yify-pop#80]
Hi guys

When I run:
<code>sudo forever start -o out.log -e err.log -s yifystart.js</code>

it will run the process but I am not able to load my site as I assume geddy doesn't load either.
I get the following error in the err.log file:

module.js:340
	throw err;
Error: Cannot find module 'geddy'
	at Function.Module._resolveFilename (module.js:338:15)
	at Function.Module._load (module.js:280:25)
	at Module.reguire (module.js:364:17)
	at require (module.js:380:17)
	at Object.<anonymous> (/home/admin/web/public_html/yifystart.js:4:13
	at Module.compile (module.js:456:26)
	at Object.Module._extensions..js (module.s:474:10)
	at Module.load (module.js:356:32)
	at Function.Module._load (module.js:312:12)
	at Function.Module.runMain (module.js:497:10)

I have installed geddy but it doesn't want to run. Any ideas on how to fix this?
Thanks!

**Comment by my90558** [comment]
Nevermind guys I got it working! I emailed G-Ray (thanks a lot!) and he helped me fix it. For anyone else who might encounter this problem here is the solution:

Simply install geddy like this:
<code>npm install geddy</code>

and NOT like this:

<code>npm install geddy</code>

Do not use the -g option when installing geddy and when you run your <code>Forever Start </code> command it should work perfectly!
